### ISSUE TITLE
Add afk kick in survival

### ISSUE THREAD

**Issue by ChillerDragon** [fokkonaut/F-DDrace#10]
Players should not be able to farm wins in survival while afk or allow rounds to start with only afks and one active player farming wins. Do not kick campers during round tho. Only if there was zero activity one whole round then throw a warning in the lobby if there is no response kick the player out of the survival minigame. So afk farming in the lobby is still possible until a round starts. And no tee is ever kicked during a round.

**Comment by fokkonaut** [comment]
Fixed in, just automatically leaves a minigame when being afk https://github.com/fokkonaut/F-DDrace/commit/49f95c86ad19544a97a0bfa277225925a19171a0
