### ISSUE TITLE
Portalgun -> Telegun

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#109]
The ability of teleporting other players is just too game breaking and should be nerfed.

**Comment by fokkonaut** [comment]
Thats the whole idea behind it.

**Comment by ChillerDragon** [comment]
Yea portal designed to balance out tele so others could follow through the portal :)

**Comment by SoulyVEVO** [comment]
Being able to teleport players straight into the freeze is definitely a bigger problem than not being able to follow them through lmao

**Comment by 23043** [comment]
@SoulyVEVO kinda true

**Comment by ChillerDragon** [comment]
> Being able to teleport players straight into the freeze is definitely a bigger problem than not being able to follow them through lmao

If it is used for pvp also the portal owner can fall in its own portal. But yea I see its a strong weapon. But still think its less cheaty or feels nicer than a tee just teleporting. I would rather nerf the portal implementation than revert to straight tele.
