### ISSUE TITLE
Make flappy use downwards shotgun to avoid freeze

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#111]
A grenade + downwards shotgun combo would should be good here since the freeze above is 2 tiles deep
![screenshot_2021-04-21_23-24-02](https://user-images.githubusercontent.com/61762251/115623013-e7d4bc80-a2f8-11eb-895b-1f65ae14b407.png)

**Comment by ChillerDragon** [comment]
Thanks for making the issue. I also thought about the left area when you mentioned it. I am not sure tho how good both weapons work if there is enough time to switch the weapons. I thought about using shotgun in this (left) area. And grenade on the right and middle of police.

**Comment by SoulyVEVO** [comment]
> Thanks for making the issue. I also thought about the left area when you mentioned it. I am not sure tho how good both weapons work if there is enough time to switch the weapons. I thought about using shotgun in this (left) area. And grenade on the right and middle of police.

ye, that require need some testing first
