### ISSUE TITLE
Police bot stuck in plot

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#113]
![screenshot_2021-04-26_15-45-45](https://user-images.githubusercontent.com/61762251/116092956-8d47b180-a6a6-11eb-851a-a21522c96da6.png)

Maybe make him auto respawn when inside the plot?

**Comment by fokkonaut** [comment]
he should kill himself after a while @ChillerDragon

**Comment by ChillerDragon** [comment]
@fokkonaut seems like the anti stuck does not catch laser wall traps. Reopen please :)
