### ISSUE TITLE
flappy bug?

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#20]
Flappy bot seems to not be able to enter police now, he gets stuck at rocket jump part and slides off the wall to freeze.

**Comment by ChillerDragon** [comment]
A screen recording or demo might help. Was the server lagging hard during that time? Did it happen multiple times?

**Comment by o-be-one** [comment]
Flappy is stuck like Souly said since my first report in Discord 4 or 5 days ago. He is like just not able to climb again at all.

**Comment by SoulyVEVO** [comment]
doesnt seem like there are any lags but flappy just stops using grenade at some point when climbing a wall

**Comment by fokkonaut** [comment]
Happens since I merged to master. I will check it
