### ISSUE TITLE
Plot hearts really at the limit freezing neighbourhood plot

### ISSUE THREAD

**Issue by o-be-one** [fokkonaut/F-DDrace#24]
Thanks K!ked for sharing  it with me.
![image](https://user-images.githubusercontent.com/4061922/96263584-2b88eb00-0f91-11eb-9e04-f65a52b43079.png)

**Comment by o-be-one** [comment]
![image](https://user-images.githubusercontent.com/4061922/96267751-309c6900-0f96-11eb-8947-360df5cbc0f9.png)
(screenshot by K!ked)

**Comment by fokkonaut** [comment]
fixed by https://github.com/fokkonaut/F-DDrace/commit/6991c49a7e41a99b6061b392aef6995add171095?w=1
