### ISSUE TITLE
Make shop item names char array not const char*

### ISSUE THREAD

**Issue by fokkonaut** [fokkonaut/F-DDrace#262]
https://github.com/fokkonaut/F-DDrace/blob/f8b07f95f40968b9d39fd6f40958d64229950dfe/src/game/server/houses/shop.h#L75

**Comment by ChillerDragon** [comment]
What is the motivation for this change?

**Comment by fokkonaut** [comment]
Good question, because I figured this will not fix the bug, but I can't remember my fix idea, because the chat headline is overflowing
