### ISSUE TITLE
[bug?] Nickname appears when using chat as ghost

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#27]
When player will send a chat message as spooky ghost then his nick will be shows above head for a short amount of time and then it dissapears again. I added question mark because im not sure if its bug or if it should work this way to keep valid nickname in chat.

**Comment by fokkonaut** [comment]
Wanted to keep the nickname. Now that there are the chat messages from players further away this could also be removed, but I am not sure about that. I think it will just stay this way
