### ISSUE TITLE
Bonus in police

### ISSUE THREAD

**Issue by TimePause3D** [fokkonaut/F-DDrace#273]
Bonus in police is a long discussed topic on Discord as well as in-game, I thought it would be a good idea to move the discussion to GitHub also. It has an exceptionally big variety of opinions, where most of them prevail against bonus. A lot of professional players left the server, because of how unfair it can get. As being in favor of most of the crowd, I want to present you some of the problems and my solution to this topic.

1. **First problem** are "blind spots" in police.

By blind spots I mean places, where a bonus player can hold a non-bonus player endlessly and him being unable to do anything about it. One of the examples of a blind spot is a police farm.

2. **Second problem** are impossible-to-counter strategies used by bonus players.

Most popular combo is jetpack and endless near the entrance of police. Bonus player can grab the non-bonus player and fly around with jetpack, making him basically unreachable for non-bonus player. Non-bonus player eventually loses his jump and dies.

 3. **Third problem** are the way-blocks near the entrance.

Bonus player having infinite jumps and camping above the entrance. Usually spamming grenades or using shotgun to mess up enemies' laser. Impossible to counter as well.

I'm sure there are many other problems that I cannot come up with right now, I just presented the most important ones.
There are also many issues related to portal and taser, but im unsure if we can count it as bonus. Let me know about this too! 
( I can present some issues about this if you guys want, just lmk c: )

**My solution for this issue** is to make tiles, which removes all bonus when entering police area, but gives bonus back after leaving it.
Here is what i define as **police area**:

![aea](https://github.com/fokkonaut/F-DDrace/assets/85745286/7b862257-212c-4a1a-aca4-0bb76650c14c)

This area should be non-bonus only. If you want to make a change in this area, let me know as well.
There would be bonus removal tiles at each of the entrance to this area, as well as warning tiles before the entrances.
The warning tiles would warn the player in chat about upcoming entrance to police and bonus removal tiles.

**Example:**

![eae](https://github.com/fokkonaut/F-DDrace/assets/85745286/0965656b-85fc-4df1-8c4e-96421a96f0d4)

We would of course patch every entrance with these tiles.

Solving this issue this way would definitely make fights in police fair and maybe bring more players too!

If you have any ideas or if you want something to add or if you want me to explain something in detail, let me know!

================================
There is also a sign ready (Credits to Terston and HeavyGeneral), it can be used for warning players about upcoming non-bonus area.

![New_Project](https://github.com/fokkonaut/F-DDrace/assets/85745286/7fcd5ff3-89c4-49bd-9497-8d8f0ea7f602)

**Comment by SoulyVEVO** [comment]
imo just remove infhook and reduce max possible bonus jumps to 3 or something so its still playable for both those more and less experienced players

**Comment by SoulyVEVO** [comment]
cuz lets be real, completely removing some items from most important area in the game would discourage many players from playing simply because of their lack of skill

**Comment by fokkonaut** [comment]
The idea was that the bonus can be loaded again when leaving "No bonus area"

**Comment by TimePause3D** [comment]
> imo just remove infhook and reduce max possible bonus jumps to 3 or something so its still playable for both those more and less experienced players

I just want to inform you that you cannot just simply remove or edit bonus out of BlmapChill. This map is supposed to be open-world when you can move around freely. I just suggested the bonus removal in a specific area, because that's where the most fights happen and bonus is bringing a disadvantage to it.


> cuz lets be real, completely removing some items from most important area in the game would discourage many players from playing simply because of their lack of skill

Not really, I would rather say it could bring more players. Players, no matter what skill gap, actually prefer fair fights over non-fair fights. The only players that might leave are the ones, who basically taught themselves how to use bonus from the beginning, but who knows, they might finally learn how to block properly 😄 

Keep in mind that you could still use bonus outside the police area.

**Comment by fokkonaut** [comment]
> I just want to inform you that you cannot just simply remove or edit bonus out of BlmapChill. 

He is talking about limiting the police area by setting jumps to 3 and removing endless in that zone only.

**Comment by fokkonaut** [comment]
I planned on saving the removed stats and load them again once someone left the "no bonus area". We just have to define what we want to be removed in that area.
Also, we need @ChillerDragon to do the map update, add a cool sign telling "Bonus free area" or "No bonus area". Then, when we have that + know which things to remove in that area, the code will be there quickly :)

**Comment by TimePause3D** [comment]
> > I just want to inform you that you cannot just simply remove or edit bonus out of BlmapChill.
> 
> He is talking about limiting the police area by setting jumps to 3 and removing endless in that zone only.

Ah, thanks for clearing that up, but still that's a bad practice, because no bonus in a certain area should mean no bonus. It isn't supposed to be friendly for people with these advantages. The goal is to provide fair fights in police. 🙂

**Comment by ChillerDragon** [comment]
# I see a different problem

I see the problems mentioned occur way stronger in other areas of the map.
Basically all areas that are open can be dominated by players with infinite jumps, endless and jetpack.

If a full bonus player wants to stop you enter the police you wont make it from spawn till the no bonus tile.
Police at least has freeze and some walls to capture full bonus players.

![bonus_areas](https://github.com/fokkonaut/F-DDrace/assets/20344300/a04d1a09-4774-4147-ac4b-f7aa2dd33ad1)

![screenshot_2024-06-20_19-44-49](https://github.com/fokkonaut/F-DDrace/assets/20344300/012f1f1f-1455-450c-bd50-9b6d09546c6b)

![screenshot_2024-06-20_19-44-38](https://github.com/fokkonaut/F-DDrace/assets/20344300/5e692add-eb73-4fd5-b11c-b1e104342aef)

# Let's try it out

In my opinion the police is the most fun place to fight full bonus players. And hunting down full bonus players to get them finally spiked is a fun boss fight which makes all the fun for me.  Also I personally need taser and 5 jumps to survive.

But it has been requested for years to do a bonus free police. I don't like it but lets try it.

# What to limit

I would like to see endless and infinite jumps removed from police. And keep the rest.
My second choice would be only 2 jumps and hammer,shotgun,grenade,laser.
About the proposed jump cap at 3. If there has to be some I would rather have it at 5.

# Where to limit

The inner area is what I would call police. But I agree that the outer area makes sense as a no bonus area.

![police](https://github.com/fokkonaut/F-DDrace/assets/20344300/814bee8b-bcdd-4718-b705-6f7b4ff0d0a0)

# How to visually mark it

I am sorry but this sign is not teeish enough. The shadow indicates flying text. The colors are too intense. The wood is not following the teeworlds style.

![image](https://github.com/fokkonaut/F-DDrace/assets/20344300/e030a16d-82a4-4160-8e28-016a7c44955c)

If it has to be a sign it should look something like this:

![screenshot_2024-06-20_19-42-48](https://github.com/fokkonaut/F-DDrace/assets/20344300/6033e4b9-f533-44dc-8c1d-1596fde2f6e6)

What would also work is a simple thin line and or some standard ddnet icons of which bonuses get deactivated.

**Comment by fokkonaut** [comment]
> I would like to see endless and infinite jumps removed from police. And keep the rest.

Agreed.

Edit: Should players get them back, once ouf of that area, like I intended it to?

**Comment by TimePause3D** [comment]
Thx for commenting @ChillerDragon! I want to point some things out in your opinion:

>I see the problems mentioned occur way stronger in other areas of the map.
Basically all areas that are open can be dominated by players with infinite jumps, endless and jetpack.

>If a full bonus player wants to stop you enter the police you wont make it from spawn till the no bonus tile.
Police at least has freeze and some walls to capture full bonus players.

These things are much easier to avoid on an open-space, because its much harder to hook a 100km/h flying tee. They can try camping the entrance, but we can't forget that you introduced a new way for raiding 😄. I am also sure that the bonus player will get tired easily, because he will not have any breaks for farming 🙂. Still, it is something we would have to experiment on to find out.

Keep also in mind that the police is the most active area on the map. People fight over it, because it contains the best farm on the map, that's why I am sure there hardly ever will be any camping players.

>In my opinion the police is the most fun place to fight full bonus players. And hunting down full bonus players to get them finally spiked is a fun boss fight which makes all the fun for me. Also I personally need taser and 5 jumps to survive.

I understand the fun of it, but what if there is a higher number of full bonus players? It is not fun anymore because of how huge the disadvantage can get. In a non-bonus fight, where you try to kill for example: 5 non-bonus players, if you are skilled enough you have a high chance of winning. Comparing to 5 bonus players vs you and your playstyle (5 jumps and taser), there are a numerous amount of strategies, where you just can't simply do anything at all other than ragequitting.

If a full-bonus drops down into police, they still have bonus if they leave the area, just not inside of it. You could still spike them and have their bonus removed 😄 

Since at the moment there is a substantially low amount of players, so there is a chance to experiment with this. If people won't like it, then we can always revert the changes.

**Comment by ChillerDragon** [comment]
> Edit: Should players get them back, once ouf of that area, like I intended it to?


Yea I like that.

**Comment by ChillerDragon** [comment]
@TimePause3D I have had already many boring fights in open space with full bonus players. It's not something theoretical. A bonus free police might not increase the occurrence. But it certainly ain't fixing it.

I also know which impossible to attack police defence strategies you talk about. Feels to me like it comes down to taste at this point. Respawning for hours trying to penetrate the unbeatable police can have something thrilling to me. But as soon as someone hooks me on the way to police I have the urge to rq. 

Spawn campers. Or magic door blockers. Or full bonus players endless hooking you from spawn or while falling (Yes that's actually quite easy with zoom) all hold me personally back from the actual gameplay. Which is attacking police. And that is just boring because the other fights outside feel often useless and have shallow, unbalanced, non rewarding gameplay.

If something has to be fixed, then the way to police should have a higher priority in my opinion. But I don't know a good fix.

The ideal gameplay for me would guarantee a undisturbed path to police. Where nobody with camping, passive tactics or bonuses has an advantage to keep players trapped in spawn. But then defending or fighting in police would allow all dirty tricks.

**Comment by TimePause3D** [comment]
I get your point with the police path, but in my opinion we should keep this as a different issue. A lot of people complained about how fights in police are completely unbalanced and I am trying to speak on behalf of them, trying to make a change. 

> Since at the moment there is a substantially low amount of players, so there is a chance to experiment with this. If people won't like it, then we can always revert the changes.

My idea is to make the area which i defined completely non-bonus and fair ( which means only 2j and weapons are allowed, eventually taser and portal, depends on if we count them as bonus ) and we could find out what people think about the change.

I haven't heard of people complaining about things you mentioned in your comment yet.

**Comment by TimePause3D** [comment]
> If something has to be fixed, then the way to police should have a higher priority in my opinion. But I don't know a good fix.

I just don't think there is any priority about these two issues, I would say both are equally important.

**Comment by fokkonaut** [comment]
![image](https://github.com/fokkonaut/F-DDrace/assets/35420825/1b77e91f-7282-45e3-b820-3a8c8a38957d)
![image](https://github.com/fokkonaut/F-DDrace/assets/35420825/003c3ff0-fe07-4761-89cf-b632372310a1)

**Comment by fokkonaut** [comment]
![image](https://github.com/fokkonaut/F-DDrace/assets/35420825/44dc2d53-7dfb-413b-96c0-550e821788e0)
![image](https://github.com/fokkonaut/F-DDrace/assets/35420825/06908edf-c357-4097-8f9e-30bea12ba303)
![sign_no_bonussign](https://github.com/fokkonaut/F-DDrace/assets/35420825/d6bab100-b7da-49d7-808b-7e37fec62157)

**Comment by fokkonaut** [comment]
Closed by https://github.com/fokkonaut/F-DDrace/commit/5bad0672d4c8c615aaada3564d00fe980351a0ee
