### ISSUE TITLE
[Idea] 1 on 1 fight system

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#28]
Sometimes you just wanna compare your skill with other player in a fully fair 1 on 1 fight. So my idea would be to add `/1on1 `command. With this command you can then type the target player that you want to fight with and optionally set a money bet and whether players can use weapons or not, for example:
`/1on1 Souly 10000 on` - would set a 1on1 fight with Souly for 10k money and enabled weapons

Players would get 1 point for each kill and whoever gets to 10 points first, wins and collets the money from bet.

We even have a big area below the map that could be used for it
![screenshot_2020-10-29_16-48-27](https://user-images.githubusercontent.com/61762251/97600094-007aae80-1a09-11eb-9071-7c257efb7d41.png)

**Comment by ChillerDragon** [comment]
+1 waiting since forever for this feature

**Comment by SoulyVEVO** [comment]
> +1 waiting since forever for this feature
> 
> Btw that area is ment for block tournaments where everyone can join and winner gets some xp and money.

something like in blockworlds? @ChillerDragon

**Comment by ChillerDragon** [comment]
> > +1 waiting since forever for this feature
> 
> > 
> 
> > Btw that area is ment for block tournaments where everyone can join and winner gets some xp and money.
> 
> 
> 
> something like in blockworlds? @ChillerDragon 

Something like in ddnet++ 😜

**Comment by BulgarianTee** [comment]
really will like a 1v1 arena or mode, but i think this shouldnt be the focus rn, also if you choose an arena, please make it smaller than the one in the picture, its just 2 people fighting

**Comment by fokkonaut** [comment]
Added already
