### ISSUE TITLE
[Idea] add additional weapon slots to shop

### ISSUE THREAD

**Issue by ChillerDragon** [fokkonaut/F-DDrace#29]
Would be nice to hold/collect more than one grenade/rilfe/shotgun at once. It should not be too expensive so beginners can bring their senpais weapons.

I thought about something around min level 5 and 10k per slot with a max of 10 or 5 slots.

**Comment by SoulyVEVO** [comment]
Seems really weird and i think that people should get weapons by themselves

**Comment by fokkonaut** [comment]
Agree with Souly, sounds weird to be able to pickup weapons more than once.
