### ISSUE TITLE
if you spawn 127 bots, some are invisible and only showing weapon

### ISSUE THREAD

**Issue by daviramoncl** [fokkonaut/F-DDrace#294]
like if u "connectdummy 127" some of them are invisible idk it must be the client

**Comment by SoulyVEVO** [comment]
its client issue since ddnet client doesnt support more than 64 players yet, close

**Comment by fokkonaut** [comment]
Can't be fixed without client support. Might come in the future, see discussion on DDNet:
https://github.com/ddnet/ddnet/pull/8542
For now I'll close this issue since we have: #291

**Comment by daviramoncl** [comment]
ok

**Comment by daviramoncl** [comment]
we still have 18.3.1
