### ISSUE TITLE
[Idea] Remove survival bonus

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#30]
Even without it, farming will be really slow, it forces people to save theirselves all the time instead of respawning.
My suggestion would be to give players +5 xp right away on normal farm tiles and +6 on police tiles.
Or maybe even giving highier xp values without sticking to the old ones like +10 xp.

**Comment by ChillerDragon** [comment]
The purpose of survival bonus is to motivate people to stay alive.
