### ISSUE TITLE
remove "/spawn" command.

### ISSUE THREAD

**Issue by daviramoncl** [fokkonaut/F-DDrace#308]
its kinda useless, why would i pay 50k just to get to spawn without respawning? at least you can make a way to disable "/spawn"

**Comment by ChillerDragon** [comment]
Why disable? Is there any problem with it?

**Comment by daviramoncl** [comment]
because its not used

**Comment by ChillerDragon** [comment]
If it's disabled it can't be used at all anymore what's the advantage of that?
