### ISSUE TITLE
when plot expires, kick all tees from the plot.

### ISSUE THREAD

**Issue by daviramoncl** [fokkonaut/F-DDrace#310]

**Comment by fokkonaut** [comment]
Could you explain why this is required?

**Comment by daviramoncl** [comment]
yea, because if the plot expires with the tee in it, the tee continues there.

**Comment by daviramoncl** [comment]
so the tee continues farming there

**Comment by fokkonaut** [comment]
> so the tee continues farming there

But somebody else will probably buy the plot soon. And in the meantime, I don't see the issue of farming there. You can't trap someone in regards of money, because the plot is cleared so they can easily kill, and as soon as another person bought it and starts editing, the tees will be kicked out.

**Comment by fokkonaut** [comment]
I'm not entirely against doing this, just trying to argue about it to see if we really need this

**Comment by daviramoncl** [comment]
is my issue accepted?
or no?
