### ISSUE TITLE
How to start a server???

### ISSUE THREAD

**Issue by Luchezr** [fokkonaut/F-DDrace#322]
How to use in?
ima little stupid

**Comment by WarHammer-z** [comment]
First you need to compile the source code.
(if you are on Windows: [Here](https://www.youtube.com/watch?v=qsoGOfBqPns&ab_channel=Prudrugtiq))
(if you are on Linux: [Here](https://www.youtube.com/watch?v=4So7peTANXw&t=185s&ab_channel=Prudrugtiq))
After compiling the server, you need to set a port forward. There are numerous videos about port forwarding, you can search on YouTube
If port forwarding is done, now you can set your server config
[Settings](https://github.com/fokkonaut/F-DDrace/blob/F-DDrace/src/game/variables.h)
[Commands](https://github.com/fokkonaut/F-DDrace/blob/F-DDrace/src/game/ddracecommands.h)
Now the server is ready!
If you get any error, or you stuck; DM me on Discord: **vahemaaa**

**Comment by timokoz** [comment]
download from the artifacts: https://github.com/fokkonaut/F-DDrace/actions/runs/11844008104
