### ISSUE TITLE
How to create an F-DDrace server via DDnet

### ISSUE THREAD

**Issue by Luchezr** [fokkonaut/F-DDrace#323]
pwease

**Comment by ChillerDragon** [comment]
Could you elaborate? I do not understand what the "via DDnet" means. F-DDrace is a standalone server. You can just build it an run it like any teeworlds server.

**Comment by Luchezr** [comment]
a

**Comment by Luchezr** [comment]
ok

**Comment by Luchezr** [comment]
How?

**Comment by ChillerDragon** [comment]
This has already been answered in https://github.com/fokkonaut/F-DDrace/issues/322
