### ISSUE TITLE
[Idea] Dont kill player when joining minigame

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#40]
Instead of killing player when he joins minigame, server would save his position and freeze his survival timer to then restore both of those things after leaving minigame.
Now minigames are pretty much dead and i think that this change could make players more likely to join them.

**Comment by fokkonaut** [comment]
Could be abused like the old /pvp_arena in DDNet++ to save yourself out of a fight. Maybe a cooldown to join, requiring 5 seconds of not moving would be okay here. But I agree, stats should be saved and restored.

**Comment by ChillerDragon** [comment]
Worked fine in ddnet++ with no move cooldown of a few secs
