### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by Boti891** [fokkonaut/F-DDrace#44]
- Remove The Air Bank and put it in plots
- put a farming place on the island
- money despawn after 1 hour if no one picked it up in plots
- plots be open on restart or starting the server

**Comment by BulgarianTee** [comment]
I can agree on some of these, like "plots be open on restart or starting the server" and "put a farming place on the island" (any more farms are welcome for me) but 1 hour despawn seems too much.. 10 minutes seems fine to me... and i think bank is at a good place as it is.

**Comment by fokkonaut** [comment]
Air bank will stay.
Farming tile on the air bank is planned already.
Small money bags are removed after 10 minutes, bigger once are never removed and even saved and loaded after restart.

**Comment by ChillerDragon** [comment]
@Boti891 please report map issues here https://github.com/DDNetPP/maps/issues since they are not related to the modification.
