### ISSUE TITLE
[Idea] Depositing coins without having to go to bank (with cooldown)

### ISSUE THREAD

**Issue by BulgarianTee** [fokkonaut/F-DDrace#45]
i know i write too much about this now but i really think its something we need. Take for example farms that are too far away: even when you are full, you cant really go to bank without dying, and dying loses all your farm progress.
https://media.discordapp.net/attachments/747743390019485719/781530700171444244/unknown.png?width=573&height=475
https://media.discordapp.net/attachments/747743390019485719/781530747293925376/unknown.png?width=654&height=475
https://media.discordapp.net/attachments/747743390019485719/781530795961090080/unknown.png?width=687&height=475
my idea to fix this is something like /deposit that deposits all your coins no matter where you are. That would be too OP normally so a cooldown is needed. My idea is either once every hour, every 6 hours or once per day. I really couldnt get any opinions on this so i hope here i can and maybe this idea to be realized.

**Comment by ChillerDragon** [comment]
Please use github native image uploads instead of 3rd party links. Also you can kill while being unfreeze without losing your money and the bank is a 3 sec fall from spawn away.
