### ISSUE TITLE
Chilli.* clanprotection can be used to cheat undeep

### ISSUE THREAD

**Issue by ChillerDragon** [fokkonaut/F-DDrace#5]

**Comment by fokkonaut** [comment]
No, https://github.com/fokkonaut/F-DDrace/blob/F-DDrace/src/game/server/entities/character.cpp#L1931

**Comment by ChillerDragon** [comment]
https://github.com/fokkonaut/F-DDrace/blob/F-DDrace/src/game/server/player.cpp#L1337

**Comment by fokkonaut** [comment]
fixed by https://github.com/fokkonaut/F-DDrace/commit/d27ba0ef91ab3c1ca3126a93dcbcccc6c3e1d054
