### ISSUE TITLE
Timeout protection

### ISSUE THREAD

**Issue by fokkonaut** [fokkonaut/F-DDrace#53]

**Comment by SoulyVEVO** [comment]
Would be good but only ddnet clients can create timeout codes, right?

**Comment by ChillerDragon** [comment]
> Would be good but only ddnet clients can create timeout codes, right?

ZillyWoods client sends timeout code as rcon command

**Comment by fokkonaut** [comment]
closed by https://github.com/fokkonaut/F-DDrace/commit/8f6b40b26f8043050eee5e7648811b28210367bb
