### ISSUE TITLE
Fix the portal and plots (portal is evil)

### ISSUE THREAD

**Issue by frutijitsu** [fokkonaut/F-DDrace#68]
add antiportal tiles or any other thing to prevent tee stealing from plots using portal.
I saw how BOB  used portal to take away my tees from my plot, he just put the portal close to my doors and a corner of dat portal was inside of the plot
so he just teleported me away and some other person threw me on the spikes and got all my money.

**Comment by ChillerDragon** [comment]
@frutijitsu can you check again? Could be fixed since https://github.com/fokkonaut/F-DDrace/commit/9e8fb28654d7565d32f2303774cbc9e049e0c1a5

**Comment by fokkonaut** [comment]
Its not, I will fix it later.
