### ISSUE TITLE
Portal Gun Issues 

### ISSUE THREAD

**Issue by Emilcha** [fokkonaut/F-DDrace#96]
When in a shield you loose portal gun, normal. But the issue happen when you want to have back your portal, you cant and you are forced to kill to get it back.

Please add something like taser, when you take a rifle you get a portal gun.

**Comment by ChillerDragon** [comment]
Yea that sounds reasonable. Is the current implementation on purpose @fokkonaut ?

**Comment by fokkonaut** [comment]
50/50 xD
I needed to decide whether I do it like this or whether portal would be that op and would not get removed by a shield, so I went with removing it until kill. Not sure if thats the best solution, but I also think there should be a way to get it back.

**Comment by Emilcha** [comment]
> 
> 
> 50/50 xD
> I needed to decide whether I do it like this or whether portal would be that op and would not get removed by a shield, so I went with removing it until kill. Not sure if thats the best solution, but I also think there should be a way to get it back.

/portalgun > give portal gun if not in inventory, **5/10 min cooldown**

**Comment by fokkonaut** [comment]
> Please add something like taser, when you take a rifle you get a portal gun.
I think that makes most sense for now.

**Comment by fokkonaut** [comment]
Fixed by https://github.com/fokkonaut/F-DDrace/commit/1ebfede1ce376cbf975e448f26c7fa54facaea48
