### ISSUE TITLE
fix tees escaping from jail

### ISSUE THREAD

**Issue by Isegrin** [fokkonaut/F-DDrace#98]
fix or nub

**Comment by ChillerDragon** [comment]
Could you explain how one can escape from jail?

**Comment by Isegrin** [comment]
They leave, change nickname, join and do the same thing again.

**Comment by 66quentin** [comment]
I didn't find your contact fokko, sorry for the off topic. Can you unban 46.193.64.144 please ?

**Comment by fokkonaut** [comment]
> I didn't find your contact fokko, sorry for the off topic. Can you unban *** please ?

You are not banned. Add me in Discord: fokkonaut#5556
